CREATE TABLE IF NOT EXISTS posts (
	id TEXT PRIMARY KEY,
	title TEXT NOT NULL,
	content TEXT NOT NULL,
	date TEXT NOT NULL,
	image_ids TEXT,
	video_ids TEXT  
	created_at TEXT DEFAULT CURRENT_TIMESTAMP
);